export const GET_PROCESS_TPL_SELECT_DATA = 'GET_PROCESS_TPL_SELECT_DATA';
export const GET_HOST_SELECT_DATA = 'GET_HOST_SELECT_DATA';
// todo 写错了 多写个 TPL
export const GET_HOST_GROUP_TPL_SELECT_DATA = 'GET_HOST_GROUP_TPL_SELECT_DATA';
// todo 写错了 多写个 GORUP
export const GET_HOST_GORUP_HOST_RELATION_SELECT_DATA = 'GET_HOST_GORUP_HOST_RELATION_SELECT_DATA';
export const GET_SALT_PATH_SELECT_DATA = 'GET_SALT_PATH_SELECT_DATA';
export const UPDATE_FIELD_SIDER = 'UPDATE_FIELD_SIDER';
